### PR TITLE
Removed urlencode function call, was double encoding links.

### PR DESCRIPTION
**Pull request by MorganDawe**

### CODE REVIEW

**Comment by daniel-dgi** [comment]
This should go against discoverygarden's fork first, not Islandora's.  Esp. considering this is just to see what Will thinks.

**Comment by willtp87** [comment]
This is mostly sane, but while we are here we should move to interpolated strings. @daniel-dgi linking names in comments would ensure I saw my mention, it's luck I noticed.  The DGI fork should not exist, I will bring this up internally.

**Comment by daniel-dgi** [comment]
Not even sure if there should've been a ticket against this repo.  Might be somewhere else double encoding.  Apparantly we don't have a fork?  Or at least, shouldn't have one?  Sorry for the hassle.

**Comment by daniel-dgi** [comment]
So then is this sane?  If so, I'll make a ticket.

**Comment by daniel-dgi** [comment]
https://jira.duraspace.org/browse/ISLANDORA-1458

**Comment by daniel-dgi** [comment]
Yeah, Morgan'll do that

**Comment by daniel-dgi** [comment]
You're too quick, @ruebot

**Comment by MorganDawe** [comment]
Added string interpolation as Will had suggested. This involves using the 't()' function in place of 'l()', as recommended here: https://api.drupal.org/api/drupal/includes!common.inc/function/l/7. In addition, i have added urlencode($pid) back in, as the t() function does not call check_plain()->htmlspecialchars, which is what i believe to be causing the appearance of double url encoding of the PID in the first place.

**Pull request merged**
